version: '3'

services:
  caddy:
    image: writing/caddy-naiveproxy:0.0.1
    restart: unless-stopped
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site/:/srv/site/
      - $PWD/caddy/log/:/var/log/
      - $PWD/caddy/caddy_data:/data
    environment:
      - DNSPODCN_APP_ID=
      - DNSPODCN_APP_TOKEN=
      - CLOUDFLARE_API_TOKEN=
    extra_hosts:
      - host.docker.internal:host-gateway

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 19445:80
    volumes:
      - $PWD/vaultwarden:/data:rw
    environment:
      - SIGNUPS_ALLOWED=false

  mind-map:
    image: shuiche/mind-map:latest
    restart: unless-stopped
    ports:
      - 18081:8080

  v2ray:
    image: zydou/v2ray:v4.45.2
    environment:
      - TZ=Asia/Shanghai  # set desired timezone
    ports:
      - 10086:10086
      - 10086:10086/udp  # comment this line if you don't need udp proxy
    volumes:
      - $PWD/v2ray/config.json:/etc/v2ray/config.json:ro
    restart: unless-stopped

networks:
  default:
    external: true
    name: web_net

volumes:
  caddy_data: {}